name: Deploy API Gateway
on: [push]

jobs:
  deploy-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'

      - name: Install CDK Dependencies
        run: npm install -g aws-cdk

      - name: npm Install in ApiGateway
        run:  npm install --prefix ApiGateway

      - name: Determine deployment stage
        id: deployment-stage
        run: |
          current_branch=$(basename "${{ github.ref }}")
          echo "current branch: $current_branch"
          
          if [ $current_branch == "SDS-7861-APIGateway-CICD" ]; then
          echo ::set-output name=stage::dev
          elif [ $current_branch == "SDS-7861-APIGateway-CICD" ]; then
          echo ::set-output name=stage::prod
          elif [ $current_branch == "SDS-7861-APIGateway-CICD" ]; then
          echo ::set-output name=stage::staging
          else
          echo "Unsupported branch for deployment"
          exit 1
          fi

      - name: Build and deploy API Gateway
        run: |
          npm run build
          cdk deploy --all --context stage=${{ steps.deployment-stage.outputs.stage }}

      - name: Output API Gateway URL
        if: success()
        run: |
          echo "API Gateway URL: $(npx cdk output ApiGatewayUrl)"
